### PR TITLE
feat: add only diff run flag

### PR DESCRIPTION
**Pull request by rusinikita**
## Proposed changes

Running mutations only for changes. A new flag `diff` runs `git diff` with reference and skip mutants outside of changes.

```
Killed: 16, Lived: 0, Not covered: 1
Timed out: 0, Not viable: 0, Skipped: 168
Test efficacy: 100.00%
Mutator coverage: 94.12%
```

Look at [docs change](https://github.com/go-gremlins/gremlins/pull/215/files#diff-c3b11fad1e53f8f988a321e5e9621308c6bbf83cb4f67d19888a1fd987f73ba2R63) for details.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/go-gremlins/gremlins/docs/CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes (`make all`)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by k3rn31** [comment]
Hello and thanks for the PR. We'll do a review ASAP. In the mean time can you pleas check the failing CI checks?

**Comment by rusinikita** [comment]
Hi! Yes, of course. I just want to get approve of solution design. If it's good for you, I'll polish PR.

**Comment by rusinikita** [comment]
@k3rn31 Hi! I'm thinking about adding this to my work projects.

How much time will a review take?

If it's not long I'll wait for a merge.

**Comment by k3rn31** [comment]
Hi! we're doing the review today, it looks promising (except for one Codeclimate linting error). I believe I'll merge soon on develop, but I'm not sure when we'll make a new release. This is a good change we'll make an extra release earlier to let this feature available right away.

**Comment by rusinikita** [comment]
Ok, thanks!

> It looks promising (except for one Codeclimate linting error)

About that. I want be in sync with your vision and wanna know a way that you prefer:

> I need advice about engine.New has 5 arguments (exceeds 4 allowed) codeclimate issue.
>
> - I can pass Diff with Option
> - I can create params struct
> - Or something else

**Comment by k3rn31** [comment]
I think the struct param is better, since we don't use it as a library and the option doesn't make sense to me.

**Comment by rusinikita** [comment]
I combined a coverage and diff into CodeData. Let me know if you want to rename it or squash/rename some commits.

**Review by k3rn31 — APPROVED** [review]
I think your implementation is sound. 
I would have taken a slightly different approach: instead of marking a mutator as "skipped", you could mark it as runnable or not (if the diff flag is active) in the same spot where it checks if it has coverage. This way no changes would have been necessary in the executor.

**Pull request merged**
