### PR TITLE
Add invert logical operations mutator

### LINKED ISSUE #137: Invert logical operators
This is a token mutator that should:

| Orig | Mutation |
|-----|----------|
| `&&` | `\|\|` |
| `\|\|` | `&&` |

INVERT_LOGICAL

Edit: `!` mutator has been moved to a separate issue (#145) because it requires a more complex work on the mutator engine.

| Orig| Mutation| 
|-----|------|
| `!` | `!!` |

### PR DESCRIPTION
**Pull request by vsvastey**
## Proposed changes

Closes #137 
A new mutator replaces && with || and vice versa.

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of
them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before
merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/go-gremlins/gremlins/docs/CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by k3rn31** [comment]
Hello and thanks for the PR. 
There's a linter failing, but it looks like a false positive, isn't it?

Could you please also update the documentation here: https://github.com/go-gremlins/gremlins/blob/535bb9d656fd7dc7c08bf8f3379e693bc661fc44/docs/docs/usage/configuration.md?plain=1#L68

And also, wire the new page here: https://github.com/go-gremlins/gremlins/blob/535bb9d656fd7dc7c08bf8f3379e693bc661fc44/docs/mkdocs.yml#L58

**Comment by k3rn31** [comment]
I disabled the dual linter, we have plenty of duplication checkers and that one seems to produce false positives.

**Review by k3rn31 — CHANGES_REQUESTED** [review]
Hello and thanks for the PR. 
There's a linter failing, but it looks like a false positive, isn't it?

Could you please also update the documentation here: https://github.com/go-gremlins/gremlins/blob/535bb9d656fd7dc7c08bf8f3379e693bc661fc44/docs/docs/usage/configuration.md?plain=1#L68

And here https://github.com/go-gremlins/gremlins/blob/main/docs/docs/usage/commands/unleash/index.md

And also, wire the new page here: https://github.com/go-gremlins/gremlins/blob/535bb9d656fd7dc7c08bf8f3379e693bc661fc44/docs/mkdocs.yml#L58

**Comment by vsvastey** [comment]
Update the commit. Rebased to main and added missed doc changes.

**Comment by vsvastey** [comment]
I've just re-asked @k3rn31 for review and by some reason review request for @giorgiaroccetti was dropped automatically. I don't have access to get it back.

**Review by k3rn31 — APPROVED** [review]

**Pull request merged**
